{% set name = 'docs' %}
{% set project_dir = environ.get('RECIPE_DIR') + '/..' %}

package:
  name: {{ name }}
  version: {{ environ.get('BOB_PACKAGE_VERSION', '0.0.1') }}

build:
  number: {{ environ.get('BOB_BUILD_NUMBER', 0) }}

requirements:
  run:
    - python
    - setuptools
    # This list should be the same as packages.txt.
    # This list should also be the same as in bob/bob conda recipe + bob and bob.devtools
    - bob
    - bob.ap
    - bob.bio.base
    - bob.bio.face
    - bob.bio.face_ongoing
    - bob.bio.gmm
    - bob.bio.htface
    - bob.bio.spear
    - bob.bio.vein
    - bob.bio.video
    - bob.blitz
    - bob.buildout
    - bob.core
    - bob.db.arface
    - bob.db.asvspoof
    - bob.db.asvspoof2017
    - bob.db.atnt
    - bob.db.atvskeystroke
    - bob.db.avspoof
    - bob.db.banca
    - bob.db.base
    - bob.db.biosecure
    - bob.db.biosecurid.face
    - bob.db.casia_fasd
    - bob.db.casiasurf
    - bob.db.casme2
    - bob.db.caspeal
    - bob.db.cbsr_nir_vis_2
    - bob.db.cohface
    - bob.db.cuhk_cufs
    - bob.db.cuhk_cufsf
    - bob.db.fargo
    - bob.db.frgc
    - bob.db.fv3d
    - bob.db.gbu
    - bob.db.hci_tagging
    - bob.db.ijba
    - bob.db.ijbc
    - bob.db.iris
    - bob.db.kboc16
    - bob.db.ldhf
    - bob.db.lfw
    - bob.db.livdet2013
    - bob.db.maskattack
    - bob.db.mnist
    - bob.db.mobio
    - bob.db.msu_mfsd_mod
    - bob.db.multipie
    - bob.db.nist_sre12
    - bob.db.nivl
    - bob.db.oulunpu
    - bob.db.pericrosseye
    - bob.db.pola_thermal
    - bob.db.putvein
    - bob.db.replay
    - bob.db.replaymobile
    - bob.db.scface
    - bob.db.siw
    - bob.db.swan
    - bob.db.utfvp
    - bob.db.uvad
    - bob.db.verafinger
    - bob.db.voicepa
    - bob.db.voxforge
    - bob.db.wine
    - bob.db.xm2vts
    - bob.db.youtube
    - bob.devtools
    - bob.extension
    - bob.fusion.base
    - bob.io.audio
    - bob.io.base
    - bob.io.image
    - bob.io.matlab
    - bob.io.video
    - bob.ip.base
    - bob.ip.binseg
    - bob.ip.color
    - bob.ip.dlib
    - bob.ip.draw
    - bob.ip.facedetect
    - bob.ip.facelandmarks
    - bob.ip.flandmark
    - bob.ip.gabor
    - bob.ip.optflow.hornschunck
    - bob.ip.optflow.liu
    - bob.ip.qualitymeasure
    - bob.ip.skincolorfilter
    - bob.ip.tensorflow_extractor
    - bob.learn.activation
    - bob.learn.boosting
    - bob.learn.em
    - bob.learn.libsvm
    - bob.learn.linear
    - bob.learn.mlp
    - bob.learn.pytorch
    - bob.learn.tensorflow
    - bob.math
    - bob.measure
    - bob.pad.base
    - bob.pad.face
    - bob.pad.vein
    - bob.pad.voice
    - bob.rppg.base
    - bob.sp
    - gridtk
test:
  commands:
    - sphinx-build {{ project_dir }}/doc {{ project_dir }}/sphinx
  requires:
    - bob-devel {{ bob_devel }}.*
    - nose
    - coverage
    - sphinx
    - sphinx_rtd_theme
    - sphinxcontrib-programoutput
    - graphviz
    - font-ttf-dejavu-sans-mono

about:
  home: https://www.idiap.ch/software/bob/
  license: BSD-3-Clause
  summary: Bob's documentation aggregation repository
  license_family: BSD
