{% set name = 'bob.docs' %}
{% set project_dir = environ.get('RECIPE_DIR') + '/..' %}

package:
  name: {{ name }}
  version: {{ environ.get('BOB_PACKAGE_VERSION', '0.0.1') }}

build:
  number: {{ environ.get('BOB_BUILD_NUMBER', 0) }}

requirements:
  run:
    - python
    - setuptools
    # This list should be the same as packages.txt.
    # This list should also be the same as in bob/bob conda recipe + bob and bob.devtools
    - bob
    - bob.devtools=5.3.0
    # LIST OF BOB PACKAGES - START
    - bob.extension
    - bob.io.base
    - bob.measure
    - bob.learn.em
    - bob.pipelines
    - bob.bio.base
    - bob.bio.face
    - bob.bio.video
    - bob.bio.vein
    - bob.bio.spear
    - bob.pad.base
    - bob.pad.face
    - bob.fusion.base
    # LIST OF BOB PACKAGES - END
test:
  commands:
    - sphinx-build {{ project_dir }}/doc {{ project_dir }}/sphinx
  requires:
    - nose {{ nose }}
    - coverage {{ coverage }}
    - sphinx {{ sphinx }}
    - sphinx_rtd_theme {{ sphinx_rtd_theme }}
    - sphinxcontrib-programoutput {{ sphinxcontrib_programoutput }}
    - graphviz {{ graphviz }}
    - font-ttf-dejavu-sans-mono {{ font_ttf_dejavu_sans_mono }}

about:
  home: https://www.idiap.ch/software/bob/
  license: BSD-3-Clause
  summary: Bob's documentation aggregation repository
  license_family: BSD
