{% set name = 'bob.docs' %}
{% set project_dir = environ.get('RECIPE_DIR') + '/..' %}

package:
  name: {{ name }}
  version: {{ environ.get('BOB_PACKAGE_VERSION', '0.0.1') }}

build:
  number: {{ environ.get('BOB_BUILD_NUMBER', 0) }}

requirements:
  run:
    - python
    - setuptools
    # This list should be the same as packages.txt.
    # This list should also be the same as in bob/bob conda recipe + bob and bob.devtools
    - bob
    - bob.devtools
    # LIST OF BOB PACKAGES - START
    - bob.buildout
    - bob.extension
    - bob.blitz
    - bob.core
    - bob.io.base
    - bob.math
    - bob.measure
    - bob.io.image
    - bob.db.base
    - bob.io.video
    - bob.io.audio
    - bob.sp
    - bob.ap
    - bob.ip.base
    - bob.ip.color
    - bob.ip.gabor
    - bob.learn.activation
    - bob.learn.linear
    - bob.learn.libsvm
    - bob.learn.mlp
    - bob.db.iris
    - bob.learn.em
    - bob.db.mnist
    - bob.db.atnt
    - bob.ip.facedetect
    - gridtk
    - bob.ip.qualitymeasure
    - bob.pipelines
    - bob.learn.tensorflow
    - bob.bio.base
    - bob.bio.gmm
    - bob.bio.face
    - bob.bio.video
    - bob.bio.vein
    - bob.pad.base
    - bob.pad.face
    - bob.fusion.base
    - bob.learn.pytorch
    - bob.ip.binseg
    # LIST OF BOB PACKAGES - END
test:
  commands:
    - sphinx-build {{ project_dir }}/doc {{ project_dir }}/sphinx
  requires:
    - bob-devel {{ bob_devel }}.*
    - nose
    - coverage
    - sphinx
    - sphinx_rtd_theme
    - sphinxcontrib-programoutput
    - graphviz
    - font-ttf-dejavu-sans-mono

about:
  home: https://www.idiap.ch/software/bob/
  license: BSD-3-Clause
  summary: Bob's documentation aggregation repository
  license_family: BSD
